//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Quiz_Id { get; set; }
        public System.DateTime Quiz_Date { get; set; }
        public int Student_Id { get; set; }
        public string Quiz_Name { get; set; }
        public int Student_Score { get; set; }
        public Nullable<int> Category_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Student Student { get; set; }
    }
}
